### ISSUE TITLE
feature request: ability to stop queue

### ISSUE THREAD

**Issue by inmarelibero** [cnwhy/axios-extra#1]
I think a method to stop queue processing and/or emptying the queue would be nice

Example:
- I load a Vue page
- 100 axios requests are put in queue and processed
- after processing 10 requests, the user navigates to another page
- => remaining 90 requests are processed, but they are useless

so I'd like to have these methods:
- `pauseQueue()`
- `resumeQueue()`
- `stopQueue()` which pauses and empties the queue

If paused, queue would automatically resume if a new request is added (maybe)

**Comment by cnwhy** [comment]
Yeah, maybe I should expose some of the queue's APIs。

**Comment by cnwhy** [comment]
https://github.com/cnwhy/axios-extra/commit/1f6c411b640f94aa52dbaaa61a40a16826c74356#diff-146cf54bda88408eb927383bdb62e9a21938000813d68591c73bfce266188ccaR86

Try it
